'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Clock, Search, Sparkles } from 'lucide-react';
import { categories, posts } from '@/lib/site-data';

const PAGE_SIZE=6;
export function InsightsBrowser(){const [category,setCategory]=useState('전체');const [query,setQuery]=useState('');const [page,setPage]=useState(1);const filtered=useMemo(()=>posts.filter(post=>(category==='전체'||post.category===category)&&(`${post.title} ${post.summary}`.toLowerCase().includes(query.toLowerCase()))),[category,query]);const total=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));const visible=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);function select(value:string){setCategory(value);setPage(1)}return <>
  <div className="flex flex-col gap-4 rounded-2xl border border-white/10 bg-white/[.035] p-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex gap-2 overflow-x-auto pb-2 lg:pb-0" aria-label="카테고리 필터">{categories.map(item=><button key={item} onClick={()=>select(item)} className={`shrink-0 rounded-full border px-4 py-2 text-xs font-bold transition ${category===item?'border-[#25f4ee]/50 bg-[#25f4ee]/10 text-[#7dfffb]':'border-white/10 text-white/48 hover:text-white'}`}>{item}</button>)}</div><label className="relative shrink-0 lg:w-64"><Search className="absolute left-3 top-3.5 size-4 text-white/35"/><span className="sr-only">인사이트 검색</span><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="키워드 검색" className="h-11 w-full rounded-lg border border-white/12 bg-black/25 pl-10 pr-3 text-sm outline-none focus:border-[#25f4ee] focus:ring-2 focus:ring-[#25f4ee]/20"/></label></div>
  {visible.length?<div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{visible.map(post=><article key={post.slug} className="group overflow-hidden rounded-2xl border border-white/10 bg-[#101216] transition hover:-translate-y-1 hover:border-[#25f4ee]/30"><Link href={`/insights/${post.slug}`} className="block"><div className="relative h-44 overflow-hidden bg-[radial-gradient(circle_at_70%_30%,rgba(37,244,238,.28),transparent_30%),radial-gradient(circle_at_22%_75%,rgba(254,44,85,.28),transparent_35%),linear-gradient(135deg,#161921,#08090b)] p-5"><span className="inline-flex rounded-full border border-white/12 bg-black/25 px-3 py-1 text-[11px] font-bold text-white/65">{post.category}</span><Sparkles className="absolute bottom-6 right-6 size-11 text-white/12"/>{post.featured&&<span className="absolute right-4 top-4 rounded bg-[#fe2c55] px-2 py-1 text-[10px] font-black">추천</span>}</div><div className="p-6"><div className="flex items-center gap-3 text-xs text-white/34"><time>{post.date}</time><span className="flex items-center gap-1"><Clock className="size-3"/>{post.readTime}</span></div><h2 className="mt-3 text-xl font-black leading-snug tracking-[-.025em] group-hover:text-[#6ffbf7]">{post.title}</h2><p className="mt-3 line-clamp-2 text-sm leading-6 text-white/48">{post.summary}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-white/70">읽어보기 <ArrowRight className="size-4"/></span></div></Link></article>)}</div>:<div className="mt-8 rounded-2xl border border-white/10 p-12 text-center text-white/45">검색 결과가 없습니다.</div>}
  <div className="mt-10 flex items-center justify-center gap-3"><button disabled={page===1} onClick={()=>setPage(page-1)} className="min-h-10 rounded-lg border border-white/12 bg-white/4 px-4 text-sm disabled:opacity-35">이전</button><span className="text-sm text-white/48">{page} / {total}</span><button disabled={page===total} onClick={()=>setPage(page+1)} className="min-h-10 rounded-lg border border-white/12 bg-white/4 px-4 text-sm disabled:opacity-35">다음</button></div>
  </>}
