'use client';

import { useState } from 'react';
import Link from 'next/link';
import { AlertCircle, Send } from 'lucide-react';

type Kind='seminar'|'brand'|'seller';
const configs:Record<Kind,{title:string;description:string;fields:{name:string;label:string;type?:string;required?:boolean;placeholder?:string}[]}>= {
  seminar:{title:'무료특강 신청',description:'한국 틱톡샵과 라이브커머스를 준비하는 핵심 내용을 안내합니다.',fields:[{name:'name',label:'이름',required:true},{name:'phone',label:'전화번호',type:'tel',required:true},{name:'email',label:'이메일',type:'email',required:true},{name:'activity',label:'현재 활동',placeholder:'브랜드 운영, 크리에이터, 예비 셀러 등'},{name:'interest',label:'관심 분야',placeholder:'틱톡샵, 라이브, 숏폼, 광고 등'}]},
  brand:{title:'브랜드 상담',description:'상품과 현재 상황을 알려주시면 적합한 실행 범위를 함께 정리합니다.',fields:[{name:'company',label:'회사명',required:true},{name:'name',label:'담당자',required:true},{name:'phone',label:'전화번호',type:'tel',required:true},{name:'email',label:'이메일',type:'email',required:true},{name:'product',label:'상품명',required:true},{name:'category',label:'상품 카테고리'},{name:'sales',label:'현재 월 매출 구간'},{name:'service',label:'희망 서비스'},{name:'message',label:'문의 내용',type:'textarea'}]},
  seller:{title:'라이브 셀러 등록',description:'활동 경험과 관심 분야를 남겨주시면 향후 교육·프로젝트 안내에 활용할 수 있도록 준비합니다.',fields:[{name:'name',label:'이름',required:true},{name:'phone',label:'연락처',type:'tel',required:true},{name:'email',label:'이메일',type:'email',required:true},{name:'channel',label:'활동 채널'},{name:'live',label:'라이브 경험'},{name:'sales',label:'판매 경험'},{name:'category',label:'관심 카테고리'},{name:'intro',label:'자기소개',type:'textarea'}]},
};

export function LeadForm({kind}:{kind:Kind}){
  const config=configs[kind]; const [agree,setAgree]=useState(false); const [message,setMessage]=useState('');
  function submit(e:React.SyntheticEvent<HTMLFormElement>){e.preventDefault(); const form=e.currentTarget; if(!form.checkValidity()||!agree){setMessage('필수 항목과 개인정보 동의를 확인해 주세요.'); form.reportValidity(); return;} setMessage('현재 폼은 저장 시스템 연결 전입니다. 입력 내용은 전송·저장되지 않았습니다. 백엔드 연결 후 접수가 활성화됩니다.');}
  return <div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-xs font-black tracking-[.16em] text-[#25f4ee]">CONTACT</p><h1 className="mt-4 text-4xl font-black tracking-[-.04em] sm:text-5xl">{config.title}</h1><p className="mt-5 leading-7 text-white/52">{config.description}</p><div className="mt-8 rounded-2xl border border-white/10 bg-white/[.035] p-5 text-sm leading-6 text-white/45"><AlertCircle className="mb-3 size-5 text-[#25f4ee]"/>현재 1차 버전에서는 입력 검증만 제공하며, 개인정보는 서버에 저장되지 않습니다.</div></div><form onSubmit={submit} className="rounded-3xl border border-white/10 bg-[#101216] p-5 sm:p-8" noValidate><div className="grid gap-5 sm:grid-cols-2">{config.fields.map(field=><label key={field.name} className={field.type==='textarea'?'sm:col-span-2':''}><span className="mb-2 block text-sm font-bold">{field.label}{field.required&&<em className="ml-1 not-italic text-[#fe2c55]">*</em>}</span>{field.type==='textarea'?<textarea name={field.name} className="min-h-32 w-full rounded-lg border border-white/12 bg-black/25 px-3 py-3 text-sm outline-none focus:border-[#25f4ee] focus:ring-2 focus:ring-[#25f4ee]/20" placeholder={field.placeholder}/>:<input name={field.name} type={field.type||'text'} required={field.required} className="h-12 w-full rounded-lg border border-white/12 bg-black/25 px-3 text-sm outline-none focus:border-[#25f4ee] focus:ring-2 focus:ring-[#25f4ee]/20" placeholder={field.placeholder}/>}</label>)}</div><label className="mt-6 flex cursor-pointer items-start gap-3 text-sm text-white/55"><input type="checkbox" checked={agree} onChange={e=>setAgree(e.target.checked)} className="mt-1 size-4 accent-[#fe2c55]"/><span>개인정보 수집 및 이용 안내를 확인했으며 이에 동의합니다. <LinkText/></span></label>{message&&<output aria-live="polite" className="mt-5 block rounded-xl border border-[#25f4ee]/22 bg-[#25f4ee]/6 p-4 text-sm leading-6 text-[#8ffefa]">{message}</output>}<button type="submit" className="mt-6 inline-flex h-12 w-full items-center justify-center gap-2 rounded-lg bg-[#fe174f] text-base font-black hover:bg-[#ff3767]">신청 내용 확인 <Send className="size-4"/></button></form></div>;
}
function LinkText(){return <Link href="/privacy" className="ml-1 underline underline-offset-4">개인정보처리방침</Link>}
