import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, BookOpen, Radio, Rss, Search, Sparkles, Tags } from 'lucide-react';
import { InsightsBrowser } from '@/components/insights-browser';
import { SiteShell } from '@/components/site-shell';
import { insightCategories, insightTags, publishedInsightPosts } from '@/lib/insights-data';
import { site } from '@/lib/site-data';

const title = '커머스 인사이트 | 틱톡·틱톡샵·라이브커머스 전문 콘텐츠';
const description = '틱톡샵, 틱톡 마케팅, 라이브커머스, 광고, 숏폼과 크리에이터 수익화 정보를 축적하는 틱톡커머스 전문 콘텐츠 허브입니다.';
const canonical = `${site.url}/insights`;

export const metadata: Metadata = {
  title: { absolute: title }, description, alternates: { canonical, types: { 'application/rss+xml': `${site.url}/rss.xml` } },
  openGraph: { title, description, url: canonical, type: 'website', locale: 'ko_KR', siteName: site.name, images: [{ url: '/og.png', width: 1200, height: 630, alt: '틱톡커머스 인사이트' }] },
  twitter: { card: 'summary_large_image', title, description, images: ['/og.png'] },
};

export default function InsightsPage() {
  const featured = publishedInsightPosts.filter((post) => post.featured).slice(0, 3);
  const collectionSchema = { '@context': 'https://schema.org', '@type': 'CollectionPage', name: title, description, url: canonical, inLanguage: 'ko-KR', isPartOf: { '@type': 'WebSite', name: site.name, url: site.url } };
  const itemListSchema = { '@context': 'https://schema.org', '@type': 'ItemList', numberOfItems: publishedInsightPosts.length, itemListElement: publishedInsightPosts.map((post, index) => ({ '@type': 'ListItem', position: index + 1, name: post.title, url: `${canonical}/${post.slug}` })) };

  return <SiteShell>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: serializeJsonLd(collectionSchema) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: serializeJsonLd(itemListSchema) }} />
    <section className="relative isolate overflow-hidden border-b border-white/8"><div className="hero-grid absolute inset-0 -z-20" aria-hidden="true" /><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_78%_30%,rgba(37,244,238,.13),transparent_28%),radial-gradient(circle_at_68%_88%,rgba(254,44,85,.16),transparent_34%)]" aria-hidden="true" /><div className="mx-auto grid max-w-[1440px] items-center gap-12 px-5 py-14 lg:grid-cols-[minmax(0,58fr)_minmax(0,42fr)] lg:px-10 lg:py-20"><div><p className="inline-flex min-h-8 items-center gap-2 rounded-full border border-[#25f4ee]/30 bg-[#25f4ee]/6 px-3 text-xs font-black tracking-[.14em] text-[#70fffb]"><Radio className="size-3.5" aria-hidden="true" /> COMMERCE INSIGHTS</p><h1 className="mt-7 max-w-[820px] text-[clamp(2.6rem,4.7vw,4.6rem)] font-black leading-[1.08] tracking-[-.045em]"><span className="block break-keep">틱톡커머스를 읽고</span><span className="block break-keep">실행으로 연결하는</span><span className="block break-keep">전문 콘텐츠 허브</span></h1><p className="mt-7 max-w-[720px] break-keep text-base leading-8 text-white/55 sm:text-lg">공식 정보와 실전 경험을 구분하고, 틱톡샵부터 콘텐츠·광고·라이브·셀러 성장까지 검색과 AI 답변에 활용하기 쉬운 구조로 축적합니다.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#all-insights" className="cta-primary">콘텐츠 검색하기 <Search className="size-4" aria-hidden="true" /></a><Link href="/free-class" className="cta-secondary">무료특강 신청</Link><a href="/rss.xml" className="cta-secondary">RSS 구독 <Rss className="size-4" aria-hidden="true" /></a></div></div><div className="rounded-[28px] border border-white/12 bg-[#101216]/94 p-5 shadow-2xl"><div className="flex items-center justify-between"><span className="text-xs font-black tracking-[.14em] text-white/35">KNOWLEDGE INDEX</span><Sparkles className="size-5 text-[#25f4ee]" aria-hidden="true" /></div><div className="mt-5 grid grid-cols-2 gap-3"><InsightMetric icon={<BookOpen className="size-5" />} value={`${publishedInsightPosts.length}`} label="공개 콘텐츠" /><InsightMetric icon={<Tags className="size-5" />} value={`${insightCategories.length}`} label="전문 카테고리" /></div><div className="mt-3 rounded-2xl border border-white/9 bg-black/22 p-5"><span className="text-xs text-white/38">주요 주제</span><div className="mt-3 flex flex-wrap gap-2">{insightCategories.slice(0, 6).map((category) => <Link key={category.slug} href={`/insights/category/${category.slug}`} className="rounded-full border border-white/9 px-3 py-2 text-xs font-bold text-white/58 hover:border-[#25f4ee]/35 hover:text-[#25f4ee]">{category.name}</Link>)}</div></div></div></div></section>

    <section className="border-b border-white/8 bg-[#090a0d]"><div className="mx-auto max-w-[1200px] px-5 py-16 lg:px-10"><div className="flex items-end justify-between gap-6"><div className="section-heading"><p>FEATURED</p><h2>먼저 읽을 인사이트</h2></div><span className="hidden text-sm text-white/35 sm:block">편집팀 추천</span></div><div className="mt-9 grid gap-4 md:grid-cols-3">{featured.map((post, index) => <Link key={post.slug} href={`/insights/${post.slug}`} className="group rounded-2xl border border-white/10 bg-white/[.035] p-6 transition hover:border-[#fe2c55]/35"><div className="flex items-center justify-between"><span className="text-xs font-black text-[#fe6689]">FEATURED {String(index + 1).padStart(2, '0')}</span><span className="text-xs text-white/28">{post.readTime}</span></div><h2 className="mt-5 text-xl font-black leading-snug group-hover:text-[#25f4ee]">{post.title}</h2><p className="mt-3 line-clamp-2 text-sm leading-6 text-white/44">{post.summary}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold">읽어보기 <ArrowRight className="size-4" aria-hidden="true" /></span></Link>)}</div></div></section>

    <section className="mx-auto max-w-[1200px] px-5 py-20 lg:px-10"><div className="section-heading"><p>TOPIC MAP</p><h2>관심 분야에서 시작하세요</h2></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{insightCategories.map((category, index) => { const count = publishedInsightPosts.filter((post) => post.category.slug === category.slug).length; return <Link key={category.slug} href={`/insights/category/${category.slug}`} className="group rounded-2xl border border-white/10 bg-white/[.03] p-6 transition hover:-translate-y-1 hover:border-[#25f4ee]/30"><div className="flex items-center justify-between"><span className={`grid size-10 place-items-center rounded-xl ${index % 2 ? 'bg-[#fe2c55]/9 text-[#fe6689]' : 'bg-[#25f4ee]/8 text-[#25f4ee]'}`}><BookOpen className="size-5" aria-hidden="true" /></span><span className="text-xs font-bold text-white/28">{count}개</span></div><h3 className="mt-5 text-lg font-black">{category.name}</h3><p className="mt-3 line-clamp-2 text-sm leading-6 text-white/42">{category.description}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-white/65">전체 보기 <ArrowRight className="size-4" aria-hidden="true" /></span></Link>; })}</div></section>

    <section id="all-insights" className="scroll-mt-24 border-y border-white/8 bg-[#090a0d]"><div className="mx-auto max-w-[1200px] px-5 py-20 lg:px-10"><div className="section-heading"><p>ALL INSIGHTS</p><h2>검색하고, 연속해서 읽으세요</h2></div><p className="mt-5 max-w-2xl break-keep leading-7 text-white/48">제목, 요약, 카테고리와 태그를 함께 검색합니다. 공개 상태의 콘텐츠만 노출됩니다.</p><div className="mt-10"><InsightsBrowser /></div></div></section>

    <section className="mx-auto max-w-[1200px] px-5 py-20 lg:px-10"><div className="grid gap-8 lg:grid-cols-[1fr_.8fr]"><div><div className="section-heading"><p>POPULAR TAGS</p><h2>세부 주제로 더 깊게 보기</h2></div><div className="mt-8 flex flex-wrap gap-3">{insightTags.map((tag) => <Link key={tag.slug} href={`/insights/tag/${tag.slug}`} className="rounded-full border border-white/10 bg-white/[.025] px-4 py-3 text-sm font-bold text-white/55 transition hover:border-[#25f4ee]/35 hover:text-[#25f4ee]">#{tag.name}</Link>)}</div></div><div className="rounded-3xl border border-[#fe2c55]/30 bg-[radial-gradient(circle_at_80%_20%,rgba(254,44,85,.14),transparent_35%),#101216] p-8"><p className="text-xs font-black tracking-[.14em] text-[#fe6689]">FROM INSIGHT TO ACTION</p><h2 className="mt-4 text-3xl font-black tracking-[-.04em]">읽은 내용을<br />내 사업에 적용하세요</h2><p className="mt-5 break-keep text-sm leading-7 text-white/48">무료특강으로 구조를 이해하고, 아카데미와 상담을 통해 상품·콘텐츠·라이브 실행으로 연결합니다.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/free-class" className="cta-primary">무료특강 신청</Link><Link href="/seller-academy" className="cta-secondary">셀러 아카데미</Link><Link href="/live-agency#consultation-form" className="cta-secondary">브랜드 운영 상담</Link></div></div></div></section>
  </SiteShell>;
}

function InsightMetric({ icon, value, label }: { icon: React.ReactNode; value: string; label: string }) { return <div className="rounded-2xl border border-white/9 bg-white/[.035] p-5"><span className="text-[#25f4ee]">{icon}</span><strong className="mt-4 block text-3xl font-black">{value}</strong><span className="mt-1 block text-xs text-white/38">{label}</span></div>; }
function serializeJsonLd(value: object) { return JSON.stringify(value).replace(/</g, '\\u003c'); }
